---
# handlers file for node_exporter
- name: restarted Node Exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags:
    - restart service