--- 
# tasks file for filebeat
- name: Обновление кэша репозиториев
  apt:
    update_cache: yes

- name: Установка деб-пакета filebeat
  apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.15.0-amd64.deb"
      state: present

- name: Включение и запуск filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: started
    daemon_reload: true

- name: Изменение прав доступа log-файлов nginx
  ansible.builtin.file:
    path: "{{ item }}"                    
    mode: '0644'                      
    state: file
  loop:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log  
  when: inventory_hostname == webservers 

- name: Изменение прав доступа log-файлов prometheus
  ansible.builtin.file:
    path: "{{ item }}"                    
    mode: '0644'                      
    state: file
  loop:
    - /var/log/prometheus/prometheus.log 
  when: inventory_hostname == 'prometheus-server'               

- name: Копирование файла конфигурации filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat