---
# defaults file for nginx_for_webservers
page_title: "Добро пожаловать на мой сайт"
content_heading: "Информационный сайт по курсовой работе"
content_body: "*ссылки на внешние сервисы, которые доступны из интернета"

bastion_host_info: "bastion-host внешний IP :62.84.116.116"

grafana_info: "http://51.250.85.251:3000"
kibana_info: "http://158.160.108.198:5601"

