---
- name: Enable TCP forwarding on the bastion host
  hosts: bastion
  become: yes
  tasks:
    - name: Uncomment the 'AllowTcpForwarding yes' line in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^s*#?s*AllowTcpForwardings+no'
        line: 'AllowTcpForwarding yes'
        backrefs: yes
        state: present
    
    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Enable packet forwarding for IPv4
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Set up NAT using iptables
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        out_interface: "eth0"
        state: present