---
# tasks file for nginx_log_exporter 
- name: Создание пользователя для Nginx Log Exporter
  user:
    name: prometheus
    system: yes
    shell: /usr/sbin/nologin
    createhome: no
    
- name: Скачивание архива Nginx Log Exporter
  get_url:
    url: "https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v{{ prometheus_nginxlog_exporter_version }}/prometheus-nginxlog-exporter_{{ prometheus_nginxlog_exporter_version }}_linux_amd64.tar.gz"
    dest: "/tmp/prometheus_nginxlog_exporter.tar.gz"

- name: Создание директории для Nginx Log Exporter
  file:
    path: "/opt/prometheus_nginxlog_exporter"
    state: directory

- name: Распаковка архива Nginx Log Exporter
  unarchive:
    src: "/tmp/prometheus_nginxlog_exporter.tar.gz"
    dest: "/opt/prometheus_nginxlog_exporter"
    remote_src: yes

- name: Копирование systemd service файла для Nginx Log Exporter
  template:
    src: prometheus_nginxlog_exporter.service.j2
    dest: "/etc/systemd/system/prometheus_nginxlog_exporter.service"
  notify: Start prometheus_nginxlog_exporter