---
# tasks file for grafana_server
- name: Установка Grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Включение и запуск Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Добавление источника данных Prometheus в Grafana
  grafana_datasource:
    url: "http://{{ hostvars['prometheus-server']['ansible_host'] }}:9090"
    name: Prometheus
    type: prometheus
    state: present
    access: proxy
    basic_auth_user: 'username'
    basic_auth_password: 'password'
    with_credentials: no
    is_default: yes
  delegate_to: localhost