---
# tasks file for grafana_server
- name: Обновление кэша репозиториев
  apt:
    update_cache: yes

- name: Скачивание деб-пакета Grafana
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb"
    dest: "/tmp/grafana_9.2.4_amd64.deb"

- name: Установка пакета Grafana
  apt:
    deb: "/tmp/grafana_9.2.4_amd64.deb"
    state: present

- name: Включение и запуск Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Копирование файла конфигурации источника данных Prometheus для Grafana
  template:
    src: prometheus.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
  notify:
    - restart grafana

- name: Импорт дашборда в Grafana
  grafana_dashboard:
    grafana_url: http://{{ grafana_external_ip }}:3000
    grafana_user: {{ grafana_admin_user }}
    grafana_password: {{ grafana_admin_password }}
    state: present
    message: "Imported by Ansible"
    overwrite: yes
    dashboard: "{{ lookup('url', 'https://grafana.com/api/dashboards/1860/revisions/37/download', validate_certs=False) }}"
  notify:
    - restart grafana