---
# tasks file for grafana_server
- name: Обновление кэша репозиториев
  apt:
    update_cache: yes

- name: Скачивание деб-пакета Grafana
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb"
    dest: "/tmp/grafana_9.2.4_amd64.deb"

- name: Установка пакета Grafana
  apt:
    deb: "/tmp/grafana_9.2.4_amd64.deb"
    state: present

- name: Включение и запуск Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Добавление источника данных Prometheus в Grafana
  grafana_datasource:
    url: "http://{{ hostvars['prometheus-server']['ansible_host'] }}:9090"
    name: Prometheus
    ds_type: prometheus
    state: present
    access: proxy   
    basic_auth_user: 'username'
    basic_auth_password: 'password'
    with_credentials: no
    is_default: yes
    sslmode: 'disable'
  delegate_to: localhost